

#发起操作
CycleTest.test
   # ... 动态代理、会话、执行器
    #映射解析过程
#1.遍历行 ResultSet.next  DefaultResultSetHandler
1.遍历行=handleRowValuesForSimpleResultMap()
2.构建对象=getRowValue()
3.创建空对象=createResultObject
#属性解析
4.解析自动属性=applyAutomaticMappings
5.手动映射=applyPropertyMappings
    5.1普通手动映射解析=prependPrefix
    5.2子查询映射解析=getNestedQueryMappingValue

#解析子查询
    #1.获取查询ID 、获取查询参数 、创建查询的key
    2.是否命中一级缓存=否
    3.直接进行实时加载=resultLoader.loadResult()==》1.遍历行
#解析comment.blog=
    #命中一级缓存时 blog只是一个占位符
    2.是否命中一级缓存.blog=是
    3.延迟加载=executor.deferLoad
#触发延迟加载  executor.queryStack==0
   触发延迟加载=executor.query
